### ISSUE TITLE
Hand controller firmware

### ISSUE THREAD

**Issue by FROGGS** [kneo/indi-bresserexos2#11]
Are you aware of this repository? https://github.com/Spitzbube/EXOS-2_GoTo_HandController

It contains a reverse engineered version of the v2.3 firmware.
This could be the base to rewrite the driver and firmware...

If you are interested, I'd like to get my hands dirty too.

**Comment by kneo** [comment]
[Yes](https://github.com/kneo/indi-bresserexos2#thanks) pretty much from the beginning, but I'd rather replace all this stuff with better motors, electronics and firmware than bothering with an vendor abendoned product. Since its Open Source, knock yourself out :)

**Comment by FROGGS** [comment]
Thanks for the notes. When you get started on something perhaps give me a ping. We are location-wise quite close nearby.
I also hang out on Dark Matters discord.
I bought my mount just a week ago, so I'm not yet ready to rip it apart. But someday perhaps.
