### ISSUE TITLE
Request help with cmake error: "indi-bresserexos2/BresserExosIIGoToDriver.cpp:124:2: error: 'defineProperty' was not declared in this scope"

### ISSUE THREAD

**Issue by Growflavor** [kneo/indi-bresserexos2#13]
Hi,

I've been following the build instructions at https://github.com/kneo/indi-bresserexos2/blob/main/Documentation/Installation.md

I am attempting a build on a device running armel Debian Buster. 

I am getting the following error during build...

`/indi-bresserexos2/build$ cmake --build .

Scanning dependencies of target indi_bresserexos2
[ 25%] Building CXX object CMakeFiles/indi_bresserexos2.dir/BresserExosIIGoToDriver.cpp.o
/home/robot/indi-bresserexos2/BresserExosIIGoToDriver.cpp: In member function 'virtual bool GoToDriver::BresserExosIIDriver::initProperties()':

/home/robot/indi-bresserexos2/BresserExosIIGoToDriver.cpp:124:2: error: 'defineProperty' was not declared in this scope
  defineProperty(&SourceCodeRepositoryURLTP);
  ^~~~~~~~~~~~~~

/home/robot/indi-bresserexos2/BresserExosIIGoToDriver.cpp:124:2: note: suggested alternative: 'deleteProperty'
  defineProperty(&SourceCodeRepositoryURLTP);
  ^~~~~~~~~~~~~~
  deleteProperty

make[2]: *** [CMakeFiles/indi_bresserexos2.dir/build.make:63: CMakeFiles/indi_bresserexos2.dir/BresserExosIIGoToDriver.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/indi_bresserexos2.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

While a different issue & platform, I did look through issue #2 hoping that might offer a clue to my situation, maybe I just missed something obvious to someone else?

/indi-bresserexos2/build$ find / -name "indiversion.h" 2>/dev/null
/usr/include/libindi/indiversion.h

/indi-bresserexos2/build$ find / -name "libindi*.so" 2>/dev/null
/usr/lib/arm-linux-gnueabi/libindidriver.so
/usr/lib/arm-linux-gnueabi/libindiAlignmentDriver.so
/usr/lib/arm-linux-gnueabi/indi/MathPlugins/libindi_SVD_MathPlugin.so

Thanks!

**Comment by kneo** [comment]
I integrated the driver into the indi-3rd-party repository. Your installed indi library may be no longer compatible, and therefore does no longer build. Please try building the source from indi-3rd-party repository as it is maintained by the indi team.

**Comment by Growflavor** [comment]
Thank you!  Just to make sure...is this the correct link for the new source I should attempt to build from:

https://github.com/indilib/indi-3rdparty/tree/master/indi-bresserexos2
