### ISSUE TITLE
Handset time set to UTC instead of local

### ISSUE THREAD

**Issue by rcreswell** [kneo/indi-bresserexos2#8]
I have discovered that when setting the Site Management Element 'UTC' the  set action changes the JOC handset time to UTC time instead of local time.  The time on the handset changes to the 'UTC Time'  setting irrespective of the 'UTC Offset' setting instead of calculating the handset local time (e.g., the offset has no impact).

I first noticed this when I used the UTC set time facility and targets were being reported as 'UdHn' (Under Horizon) on the mount's handset when planetarium software indicated that they weren't.

Note:  I entered the offset as -7 (W08 time zone in daylight savings).

**Comment by kneo** [comment]
Yes, see issue #6, its already fixed in the latest release. You can wait until your distributor updates the packages, or build the driver yourself using the latest main branch.

**Comment by rcreswell** [comment]
The behavior was exhibited on the latest main branch build.  I cleared the old installation out and started fresh just to be sure.  I also  varied the UTC offset setting to see if there was any impact on the handset time setting but there was none.  Whatever is put in the element 'UTC' is the time that the handset is set to.  Any value placed in 'UTC Offset' has no impact on the handset time.

As a work around, the handset picks up local time when power is applied to the mount controller (provided you don't wait any period). As long as you don't try to use the INDI Control Panel's Site Management Element 'UTC', everything performs normally.

Regards and thanks again for the development of this driver.

Ron

**Comment by kneo** [comment]
I think I fixed it, you can check out the latest main branch, and retry. There were also still some issues with the location, I hopefully fixed those too.

**Comment by rcreswell** [comment]
I removed the prior build and reinstalled the main branch from scratch.  After testing the Site Management Element 'UTC' and 'UTC Offset' the INDI Control Panel set action still places the Exos-2gt handset time to UTC time.  Varying the 'UTC Offset' parameter also continues to have no effect.

Lat/Lon entries continue to work fine.

**Comment by kneo** [comment]
you need to click the "time" button followed by "OK" in the dialog box, the "set" button only affects the geo location setting.

**Comment by rcreswell** [comment]
Kevin,

The INDI Control Panel in KStars does, as you indicate,  show 'Time' button for the UTC parms but other INDI Control Panel clients like IPARCOS and the iPhone CloudMakers iOS app show 'Set' for the UTC parms instead.

In any case, I tried all three clients (including the use of 'Time'/'OK' buttons in the KStars client) with the same effect.  The UTC field entry becomes the handset time regardless of the 'UTC Offset' entry.

Ron

**Comment by kneo** [comment]
I'm sorry to steal your time! I looked through the other drivers shipped with indi, and shamelessly stole code from a celestron driver which happens to work in a similar way. You now should be able to set the utc time and the hand box should adjust accordingly.

**Comment by rcreswell** [comment]
Thanks Kevin.  I'm the one stealing your time. I'd like to personally shake your hand for all of this skilled workmanship if it were possible.

Regards,

Ron

**Comment by kneo** [comment]
Thanks for your feedback, I take it its working now expected and the issue can be closed?

**Comment by rcreswell** [comment]
I am pleased to report that the UTC time setting feature is now working correctly with UTC and offset entry setting the handset to the correct local time.  Thanks once again Kevin.

**Comment by kneo** [comment]
I forgot to remove a wrong offset so the year was wrong ... the latest checkout will fix that. Never ever mess with time ...

**Comment by rcreswell** [comment]
Ya, I saw that.  The year was 3921 (1900 years future).  The number 1900 seemed like a clue to me.  You were one step ahead of me.  

 

Best Regards Kevin,

 

Ron Creswell
